# Generated by Django 2.2.6 on 2020-01-29 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigator',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
