# Generated by Django 2.2.6 on 2020-01-29 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0002_navigator_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigator',
            name='section',
            field=models.TextField(null=True),
        ),
    ]
