# Generated by Django 2.2.6 on 2020-01-29 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0003_navigator_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigator',
            name='template_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
