# Generated by Django 2.2.6 on 2020-02-03 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0005_auto_20200203_0927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navigator',
            name='subname',
        ),
        migrations.AddField(
            model_name='navigator',
            name='subname',
            field=models.ManyToManyField(null=True, to='information.Subnavigator'),
        ),
    ]
