# Generated by Django 2.2.6 on 2020-02-03 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0007_auto_20200203_0942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navigator',
            name='subname',
        ),
        migrations.AddField(
            model_name='subnavigator',
            name='subname',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='information.Subnavigator'),
        ),
    ]
