# Generated by Django 2.2.6 on 2020-02-03 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0009_auto_20200203_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subnavigator',
            name='subname',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub', to='information.Navconstruct'),
        ),
    ]
