# Generated by Django 2.2.6 on 2020-02-04 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0011_subsubnav'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('href', models.URLField(null=True)),
                ('classname', models.CharField(max_length=30)),
                ('text', models.TextField(null=True)),
                ('social', models.BooleanField()),
            ],
        ),
    ]
