# Generated by Django 2.2.6 on 2020-02-05 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0012_social'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Navigator',
        ),
        migrations.AlterField(
            model_name='social',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
