# Generated by Django 2.2.6 on 2020-02-06 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0014_footer_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='subname',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='footersub', to='information.Subnavigator'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='hreflogo',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
