# Generated by Django 2.2.6 on 2020-02-06 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0016_auto_20200206_1049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footer',
            name='hreflogo',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='subname',
        ),
        migrations.AddField(
            model_name='footer',
            name='classul',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='footercont',
            name='classname',
            field=models.CharField(max_length=100),
        ),
    ]
