# Generated by Django 2.2.6 on 2020-02-06 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0018_auto_20200206_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='subname',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='textsub', to='information.Footer'),
        ),
    ]
