# Generated by Django 2.2.6 on 2020-02-06 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0019_auto_20200206_1148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='text',
            old_name='text',
            new_name='footertext',
        ),
    ]
