# Generated by Django 2.2.6 on 2020-02-06 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0020_auto_20200206_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='title',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
