# Generated by Django 2.2.6 on 2020-02-06 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0021_text_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='footercont',
            name='classdiv',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
