# Generated by Django 2.2.6 on 2020-02-07 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0024_auto_20200207_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footercont',
            name='subname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='information.Navconstruct'),
        ),
    ]
