# Generated by Django 2.2.6 on 2020-02-07 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0025_auto_20200207_0815'),
    ]

    operations = [
        migrations.RenameField(
            model_name='footercont',
            old_name='subname',
            new_name='projname',
        ),
    ]
