# Generated by Django 2.2.6 on 2020-02-07 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0026_auto_20200207_0833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footercont',
            name='projname',
        ),
        migrations.AddField(
            model_name='subsubnav',
            name='projname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='information.Navconstruct'),
        ),
    ]
