# Generated by Django 2.2.6 on 2020-02-07 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0028_auto_20200207_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subnavigator',
            name='projname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='information.Footercont'),
        ),
    ]
