# Generated by Django 2.2.6 on 2020-02-10 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0030_page_slider'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='text',
            new_name='textdown',
        ),
        migrations.AddField(
            model_name='page',
            name='textup',
            field=models.TextField(blank=True),
        ),
    ]
