# Generated by Django 2.2.6 on 2020-02-10 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0031_auto_20200210_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='projname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subslider', to='information.Subnavigator'),
        ),
    ]
