# Generated by Django 2.2.6 on 2020-02-13 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0034_auto_20200213_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagenext',
            name='titleparagraph',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='pagenext',
            name='titlecoloumn',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
