# Generated by Django 2.2.6 on 2020-02-13 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0036_projects'),
    ]

    operations = [
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('href', models.CharField(blank=True, max_length=100)),
                ('src', models.CharField(blank=True, max_length=100)),
                ('hrefpage', models.CharField(blank=True, max_length=100)),
                ('projectname', models.CharField(blank=True, max_length=200)),
                ('example', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='example', to='information.Projects')),
            ],
        ),
    ]
