# Generated by Django 2.2.6 on 2020-02-22 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0037_example'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='example',
            name='hrefpage',
        ),
        migrations.AddField(
            model_name='example',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Short',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predescription', models.TextField(blank=True)),
                ('namecategory', models.CharField(max_length=30)),
                ('caregory', models.CharField(max_length=100)),
                ('namefokus', models.CharField(max_length=30)),
                ('fokus', models.CharField(max_length=100)),
                ('namesite', models.CharField(max_length=30)),
                ('site', models.CharField(max_length=100)),
                ('nameduration', models.CharField(max_length=30)),
                ('duration', models.CharField(max_length=100)),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='short', to='information.Example')),
            ],
        ),
        migrations.CreateModel(
            name='Pictures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='information.Example')),
            ],
        ),
        migrations.CreateModel(
            name='Pageproject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urlvideo', models.URLField(blank=True, max_length=100)),
                ('blockquote', models.TextField(blank=True)),
                ('paragraph', models.TextField(blank=True)),
                ('titlenext', models.CharField(blank=True, max_length=30)),
                ('textnext', models.TextField(blank=True)),
                ('titlecoloumn', models.CharField(blank=True, max_length=100)),
                ('titleparagraph', models.CharField(blank=True, max_length=100)),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pageproject', to='information.Example')),
            ],
        ),
    ]
