# Generated by Django 2.2.6 on 2020-02-22 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0039_auto_20200222_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='pictures',
            name='href1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pictures',
            name='href2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pictures',
            name='href3',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
