# Generated by Django 2.2.6 on 2020-02-22 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0042_auto_20200222_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageproject',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
