# Generated by Django 2.2.6 on 2020-02-22 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0043_pageproject_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pageproject',
            name='title',
        ),
    ]
