# Generated by Django 2.2.6 on 2020-02-28 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0044_remove_pageproject_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pageproject',
            old_name='blockquote1',
            new_name='blockquote',
        ),
        migrations.RenameField(
            model_name='pageproject',
            old_name='paragraph1',
            new_name='paragraph',
        ),
        migrations.RenameField(
            model_name='pageproject',
            old_name='textnext1',
            new_name='textnext',
        ),
        migrations.RenameField(
            model_name='pageproject',
            old_name='titlecoloumn1',
            new_name='titlecoloumn',
        ),
        migrations.RenameField(
            model_name='pageproject',
            old_name='titlenext1',
            new_name='titlenext',
        ),
        migrations.RenameField(
            model_name='pageproject',
            old_name='titleparagraph1',
            new_name='titleparagraph',
        ),
        migrations.RenameField(
            model_name='pageproject',
            old_name='urlvideo1',
            new_name='urlvideo',
        ),
        migrations.AlterField(
            model_name='subnavigator',
            name='subname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub', to='information.Navconstruct'),
        ),
    ]
