# Generated by Django 2.2.6 on 2020-03-02 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0046_faq_faqblock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('answer', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contdecr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(blank=True, max_length=100)),
                ('title2', models.CharField(blank=True, max_length=100)),
                ('title3', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
