# Generated by Django 2.2.6 on 2020-03-04 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0050_textslider_textbldown'),
    ]

    operations = [
        migrations.AddField(
            model_name='textslider',
            name='clas',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
