# Generated by Django 2.2.6 on 2020-03-04 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0053_mpage_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='navconstruct',
            name='hreflogo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='navconstruct',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subnavigator',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subsubnav',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
