# Generated by Django 2.2.6 on 2020-03-12 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0055_auto_20200305_0758'),
    ]

    operations = [
        migrations.AddField(
            model_name='navconstruct',
            name='title',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='subnavigator',
            name='title',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='subsubnav',
            name='title',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
