# Generated by Django 2.2.6 on 2020-03-16 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0057_auto_20200316_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='example',
            name='description',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='example',
            name='keywords',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
