# Generated by Django 2.2.6 on 2020-03-16 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0058_auto_20200316_1745'),
    ]

    operations = [
        migrations.RenameField(
            model_name='navconstruct',
            old_name='description',
            new_name='descrtionmeta',
        ),
        migrations.RenameField(
            model_name='navconstruct',
            old_name='keywords',
            new_name='keywordsmeta',
        ),
        migrations.RenameField(
            model_name='subnavigator',
            old_name='description',
            new_name='descrtionmeta',
        ),
        migrations.RenameField(
            model_name='subnavigator',
            old_name='keywords',
            new_name='keywordsmeta',
        ),
        migrations.RenameField(
            model_name='subsubnav',
            old_name='description',
            new_name='descrtionmeta',
        ),
        migrations.RenameField(
            model_name='subsubnav',
            old_name='keywords',
            new_name='keywordsmeta',
        ),
    ]
