# Generated by Django 2.1 on 2020-03-19 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0059_auto_20200316_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='example',
            name='href',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='example',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='example',
            name='src',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='pictures',
            name='href1',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
