# Generated by Django 2.1 on 2020-03-19 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0060_auto_20200319_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etapy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('answer', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
