# Generated by Django 2.1 on 2020-03-19 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0061_etapy'),
    ]

    operations = [
        migrations.AddField(
            model_name='etapy',
            name='href1',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
